### ISSUE TITLE
TAKE_ITEM not updating inventory in GUI.

### ISSUE THREAD

**Issue by TheSleuthy** [PokeSkies/SkiesGUIs#1]
The "TAKE_ITEM" action type doesn't actively update the GUI inventory when you perform the action. This happens regardless of requirement being there.
![image_2023-11-03_062521048](https://github.com/PokeSkies/SkiesGUIs/assets/121482349/690f5f83-8f6f-48ca-b1ca-e8f91ac5eb6c)

**Comment by Stampede2011** [comment]
The new `REFRESH_GUI` action in v1.3.0 should resolve this issue. Will double check
